name: CI
on: 
  pull_request:
    branches: [ main ]

jobs:
  # Run_flutter_test_and_analyze:
  #   name: Run flutter test and analyze
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Set up Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       channel: 'stable'
  #       # flutter-version: ${{ env.FLUTTER_VERSION }} # you can also specify exact version of flutter

  #   - name: Get pub dependencies
  #     run: flutter pub get

  #   - name: Flutter analyze
  #     run: flutter analyze

  #   - name: Flutter test
  #     run: flutter test



  # build_ios:
  #   name: Build Flutter (iOS)
  #   runs-on: macos-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'

  #     # - name: Get pub dependencies
  #     #   run: flutter pub get
  #     # - run: flutter clean
  #     - name: Build IOS App
  #       run: flutter build ios --release --no-codesign


  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build Android App
        run: flutter build appbundle

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: android-build-files
    
  deploy:
    needs: build_android
    runs-on: ubuntu-latest
    steps: 
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: android-build-files

  # slack:
  #   name: Send message to slack
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Notification Slack
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: test
  #         SLACK_TITLE: Post Title
  #         SLACK_USERNAME: BotCI
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_MESSAGE: "This is your custom message."

  slack_second_var:
    name: Send message to slack
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

          # "blocks": [
          #       {
          #         "type": "section",
          #         "text": {
          #           "type": "mrkdwn",
          #           "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n${{ steps.androidBuildId.outputs.download-path }}"
          #         }
          #       }
          #     ]